In [2]:
!pip install numpy

In [3]:
import numpy as np


### Task 1: Creating Arrays

In [4]:
arr_1_dimension = np.arange(1, 11)

In [5]:
arr_2_dimension = np.random.randint(1, 11, size=(3, 3))

In [7]:
print("1D Array:")
print(arr_1_dimension)

print("\n2D Array:")
print(arr_2_dimension)

1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2D Array:
[[10  7  9]
 [ 7  9  7]
 [ 9  6 10]]


### Task 2: Array Operations

In [9]:
# Sum, mean, max
sum_val = arr_1_dimension.sum()
mean_val = arr_1_dimension.mean()
max_val = arr_1_dimension.max()

print("Sum:", sum_val)
print("Mean:", mean_val)
print("Max:", max_val)

# Multiply all elements by 2
multiplied = arr_1_dimension * 2
print("\nMultiplied by 2:")
print(multiplied)

# Replace values > 5 with 0
modified = arr_1_dimension.copy()
modified[modified > 5] = 0

print("\nValues > 5 replaced with 0:")
print(modified)


Sum: 55
Mean: 5.5
Max: 10

Multiplied by 2:
[ 2  4  6  8 10 12 14 16 18 20]

Values > 5 replaced with 0:
[1 2 3 4 5 0 0 0 0 0]
